In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np


In [3]:
!ls

01_Numpy.ipynb Documents      Library        Music          Public
Desktop        Downloads      Movies         Pictures


In [4]:
ls

01_Numpy.ipynb  Documents/      Library/        Music/          Public/
Desktop/        Downloads/      Movies/         Pictures/


In [5]:
np.version.version

'1.24.2'

In [6]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [7]:
type(a)

list

In [8]:
sqrs = [i*i for i in a]
sqrs

[1, 4, 9, 16, 25]

In [9]:
 c = np.array(a)
type(c)

numpy.ndarray

In [10]:
c


array([1, 2, 3, 4, 5])

In [11]:
c**2

array([ 1,  4,  9, 16, 25])

In [12]:
sqr_list = list(c**2
               )

In [13]:
sql_list

NameError: name 'sql_list' is not defined

In [14]:
sqr_list

[1, 4, 9, 16, 25]

In [1]:
%timeit [i*i for i in range(100000)]

2.98 ms ± 4.64 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [2]:
np_a = np.array(range(100000))

NameError: name 'np' is not defined

In [3]:
import numpy as np


In [4]:
np_a = np.array(range(100000))

In [5]:
%timeit np_a*np_a

29.9 µs ± 15 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [6]:
%timeit np_a**2

23.5 µs ± 6.73 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [7]:
np.array([1,2,3])

array([1, 2, 3])

In [17]:
c = np.array([[1,2,1],[1,2,3]])

In [9]:
np_a.dtype



dtype('int64')

In [10]:
np_a.ndim

1

In [11]:
np_a.shape

(100000,)

In [13]:
c

array([[1, 2],
       [1, 2]])

In [14]:
c.ndim

2

In [15]:
c.shape

(2, 2)

In [18]:
c.shape


(2, 3)

In [19]:
c.shape()

TypeError: 'tuple' object is not callable

In [20]:
c.shape

(2, 3)

In [21]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])