In [1]:
import numpy as np


In [2]:
a = np.arange(1,10,1.0)

In [3]:
a


array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
a[2:4]

array([3., 4.])

In [5]:
a[2:4] = [1,2]

In [6]:
a

array([1., 2., 1., 2., 5., 6., 7., 8., 9.])

In [7]:
b = np.arange(1,10,1)

In [8]:
b


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
b[1:3]= 3.0

In [12]:
b


array([1, 3, 3, 4, 5, 6, 7, 8, 9])

In [14]:
b


array([1, 3, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b[1:3]= 6.5

In [16]:
b

array([1, 6, 6, 4, 5, 6, 7, 8, 9])

In [17]:
b


array([1, 6, 6, 4, 5, 6, 7, 8, 9])

In [18]:
b.dtype()

TypeError: 'numpy.dtype[int64]' object is not callable

In [19]:
b.dtype


dtype('int64')

In [20]:
b = np.array(b,dtype='float')


In [21]:
b


array([1., 6., 6., 4., 5., 6., 7., 8., 9.])

In [22]:
b.dtype

dtype('float64')

In [23]:
b<6

array([ True, False, False,  True,  True, False, False, False, False])

In [24]:
b


array([1., 6., 6., 4., 5., 6., 7., 8., 9.])

In [25]:
b[b<6]

array([1., 4., 5.])

In [26]:
a = np.arange(1,100)

In [27]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [28]:
a[a%3]

array([2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2,
       3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3,
       1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2,
       3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1])

In [29]:
a%3


array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2,
       0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0,
       1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1,
       2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0])

In [30]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [31]:
a[a/3]

IndexError: arrays used as indices must be of integer (or boolean) type

In [32]:
a/3


array([ 0.33333333,  0.66666667,  1.        ,  1.33333333,  1.66666667,
        2.        ,  2.33333333,  2.66666667,  3.        ,  3.33333333,
        3.66666667,  4.        ,  4.33333333,  4.66666667,  5.        ,
        5.33333333,  5.66666667,  6.        ,  6.33333333,  6.66666667,
        7.        ,  7.33333333,  7.66666667,  8.        ,  8.33333333,
        8.66666667,  9.        ,  9.33333333,  9.66666667, 10.        ,
       10.33333333, 10.66666667, 11.        , 11.33333333, 11.66666667,
       12.        , 12.33333333, 12.66666667, 13.        , 13.33333333,
       13.66666667, 14.        , 14.33333333, 14.66666667, 15.        ,
       15.33333333, 15.66666667, 16.        , 16.33333333, 16.66666667,
       17.        , 17.33333333, 17.66666667, 18.        , 18.33333333,
       18.66666667, 19.        , 19.33333333, 19.66666667, 20.        ,
       20.33333333, 20.66666667, 21.        , 21.33333333, 21.66666667,
       22.        , 22.33333333, 22.66666667, 23.        , 23.33

In [33]:
a[a%3 == 0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [1]:
a

NameError: name 'a' is not defined

In [2]:
import numpy as np


In [3]:
a = np.arange(1,100)

In [4]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [9]:
a[˜(a%2==0)]

SyntaxError: invalid character '˜' (U+02DC) (3416645005.py, line 1)

In [10]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
a[˜(a%2 == 0)]

SyntaxError: invalid character '˜' (U+02DC) (2330497106.py, line 1)

In [12]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
a = a[a%2==0]

In [14]:
a


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [15]:
ã

NameError: name 'ã' is not defined

In [16]:
mask1 = (a%2==0)

In [17]:
mask2 = (a%5==0)

In [18]:
a


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [19]:
b = a[mask1 & mask2]

In [20]:
b

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
b


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [22]:
c = a[mask1 | mask2]

In [23]:
c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [24]:
a.header

AttributeError: 'numpy.ndarray' object has no attribute 'header'

In [25]:
a.headers()

AttributeError: 'numpy.ndarray' object has no attribute 'headers'

In [26]:
a.ndim


1

In [27]:
a.shape

(49,)

In [29]:
b = np.array([4,5,6,7,1,2,3])
b

array([4, 5, 6, 7, 1, 2, 3])

In [30]:
np.sort(b)

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
b

array([4, 5, 6, 7, 1, 2, 3])

In [32]:
b.sort()

In [33]:
b

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
np.mean(b)

4.0

In [35]:
a.mean

<function ndarray.mean>

In [36]:
a.mean()

50.0

In [37]:
b.mean()

4.0

In [1]:
import numpy as np


zsh:1: command not found: gdown


In [4]:
!pip3 install gdown

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 1.5 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 991.3 kB/s eta 0:00:00 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 3.7 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.0/123.0 kB 5.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.9/140.9 kB 5.2 MB/s eta 0:00:00
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [5]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

zsh:1: command not found: gdown


In [6]:
!gdown

zsh:1: command not found: gdown


In [7]:
!pip3 show gdown

Name: gdown
Version: 4.7.1
Summary: Google Drive direct download of big files.
Home-page: http://github.com/wkentaro/gdown
Author: Kentaro Wada
Author-email: www.kentaro.wada@gmail.com
License: MIT
Location: /Users/amb/Library/Python/3.9/lib/python/site-packages
Requires: beautifulsoup4, filelock, requests, six, tqdm
Required-by: 


In [8]:
!echo $PATH

/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin


In [9]:
!pip3 show gdown | grep Location

Location: /Users/amb/Library/Python/3.9/lib/python/site-packages


In [10]:
!export PATH=$PATH:/Users/amb/Library/Python/3.9/lib/python/site-packages

In [18]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

zsh:1: command not found: gdown


In [12]:
echo $PATH

SyntaxError: invalid syntax (2593410762.py, line 1)

In [13]:

!echo $PATH

/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin


In [14]:
!nano ˜/.bashrc

7  UW PICO 5.09                           New Buffer                             ^G Get Help  ^O WriteOut  ^R Read File ^Y Prev Pg   ^K Cut Text  ^C Cur Pos   ^X Exit      ^J Justify   ^W Where is  ^V Next Pg   ^U UnCut Text^T To Spell                                                                                  [ New file ]  UW PICO 5.09                        File: ˜/.bashrc                           ^G Get Help  ^O WriteOut  ^R Read File ^Y Prev Pg   ^K Cut Text  ^C Cur Pos   ^X Exit      ^J Justify   ^W Where is  ^V Next Pg   ^U UnCut Text^T To Spell                                                                                  [ line 1 of 1 (100%), character 0 of 0 (0%) ]

In [15]:

!

In [17]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

zsh:1: command not found: gdown


In [19]:
!gdown

zsh:1: command not found: gdown


In [20]:
gdown

NameError: name 'gdown' is not defined

In [21]:
pip3

NameError: name 'pip3' is not defined

In [22]:
!gdown

zsh:1: command not found: gdown


In [23]:
echo "export PATH=\"`python3 -m site --user-base`/bin:\$PATH\"" >> ~/.bashrc

SyntaxError: invalid syntax (2958997092.py, line 1)

In [24]:
!echo "export PATH=\"`python3 -m site --user-base`/bin:\$PATH\"" >> ~/.bashrc

In [25]:
!source ~/.bashrc


In [26]:
!gdown

zsh:1: command not found: gdown


In [ ]:
!nano ˜/.bashrc


In [ ]:
!pip3 install gdown

In [ ]:
!gdown --version

In [ ]:
a = 10

In [ ]:
a